version: '3'

services:
  db:
    image: postgres:14.1
    container_name: teslo_db
    restart: unless-stopped 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data